### ISSUE TITLE
Rename repository to recetox-waveica?

### ISSUE THREAD

**Issue by hechth** [RECETOX/WaveICA#9]
@martenson @maximskorik as this repository now contains an altered version of WaveICA, should we follow along with what we did in other repositories where we changed the packages and rename this to `recetox-waveica` and the R package to `recetox.waveica`, just to be concise?

This change should then also be reflected in the [bioconda](https://anaconda.org/bioconda/r-recetox-waveica) package (where this is already the case) and the galaxy tools?

**Comment by martenson** [comment]
Possibly. I do not have a strong opinion on how this repo should be named -- it is clearly a fork. As long as the bioconda package namespace is ours, which is the case already, I do not expect any confusion. 

In toolshed we can use recetox_waveica as suggested.

**Comment by maximskorik** [comment]
I'd agree that we should rename the repository to `recetox-waveica`. I'm not sure about the Galaxy tool though. Unlike, say, `xmsannotator`, where we improved the tool in various ways, our version of `WaveICA` does exactly the same thing in exactly the same way (from Galaxy-user's perspective). So prepending the name with `recetox` may be unjustified and confusing.

**Comment by martenson** [comment]
Sounds fair. Do we have any ambitions to modify waveica in the future to justify the recetox namespace?

**Comment by hechth** [comment]
> Sounds fair. Do we have any ambitions to modify waveica in the future to justify the recetox namespace?

Not short term at least.
